<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Version>1.1.1</Version>
		<AssemblyVersion>1.1.1</AssemblyVersion>
		<FileVersion>1.1.1</FileVersion>

		<Title>SerienStream/AniWorld API</Title>
		<Authors>IcySnex</Authors>
		<Company />
		<Description>API to search &amp; download series/anime from s.to/aniworld.to</Description>
		<PackageProjectUrl>https://github.com/IcySnex/SerienStreamAPI</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<RepositoryUrl>https://github.com/IcySnex/SerienStreamAPI/tree/main</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>scraper;series;anime,serienstream;aniworld;downloading</PackageTags>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<!--<GenerateDocumentationFile>true</GenerateDocumentationFile>-->
		<PackageReleaseNotes>
			- Fixed "Moved Permanently" error for specific s.to hosts
			- Updated DownloadClient progress callback for newer FFmpeg versions
		</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
	</ItemGroup>
</Project>
